var num1=7;
var num2=6;
console.log(num1+num2);
var sellingprice=199;
var listingprice=799;
var discountpercent=((listingprice-sellingprice)/listingprice)*100;
console.log("discount percentage is:"+discountpercent);
Discountpercentage=Math.round(discountpercent);
console.log(Discountpercentage + "% off");
var result=listingprice>sellingprice;
console.log(result);